エラー表示うまくいかない
Yappiyapi/05_learning_plan pull request #1
Opened 2020-02-11 18:52 UTC by Yappiyapi

お疲れ様です。

検索してもでてこない(うまくワードを検索できてない？)ので助言ほしいです。

【うまくいかない点】
①エラー表示はできているが片方だけ表示することができない
②時間表示するコード変えたが期限切れ赤字にできない
![スクリーンショット 2020-02-12 3 11 12](https://user-images.githubusercontent.com/58411038/74267481-78089080-4d49-11ea-88ac-be5466117305.png)
【自分的に思った点】
①は↓のコード部分が間違っているのではと思ってコードを変えたりしたがだめ
![スクリーンショット 2020-02-12 3 44 31](https://user-images.githubusercontent.com/58411038/74268109-a5a20980-4d4a-11ea-85f5-f2fefbb82043.png)
②は↓のコード部分でカリキュラムヒントのif文のところが正しく使えていないのかなと。
![スクリーンショット 2020-02-12 3 47 19](https://user-images.githubusercontent.com/58411038/74268292-f87bc100-4d4a-11ea-9d4b-8ae1dda18fa0.png)
一度確認お願いします。

2020-02-12 04:53 UTC, Arisaarisa commented on index.php
> +      <?php if (date('Y-m-d') >= $plan['due_date']) : ?>
②期限切れ日付が変わらない問題
ここの条件分岐はforeachのすぐ下に移動させてみてください！

2020-02-12 04:53 UTC, Arisaarisa commented on index.php
> +  <ul class="expired">
②クラスの指定場所ですが、`<li>`タグに指定した方がよさそうです！
cssファイルの中も指定先は`.expired`だけで大丈夫です！

2020-02-12 04:53 UTC, Arisaarisa commented on index.php
> +    $errors['title'] = '学習内容を入力してください';
①エラー表示かわらない問題
ここの`title`や`due_date`と連携がとれているところがhtmlにないのでエラーが両方出てしまします！
htmlのそれぞれinputの中にnameで繋がるように指定してあげてください！

2020-02-12 04:53 UTC, Arisaarisa commented on index.php
> +        <input type="text">
①

2020-02-12 04:53 UTC, Arisaarisa commented on index.php
> +        <input type="date" name="" id="">
①

2020-02-12 04:53 UTC, Arisaarisa commented on index.php
> +      <?php else : ?>
②elseでそれ以外のリストはになるのでもう一つ`<li>`が必要になります！

2020-02-12 16:29 UTC, Yappiyapi commented on index.php
> +      <?php else : ?>
①部分は理解でき修正できたんですが、②のelseの<li>の切替部分がよく理解できません。
点が2つになってしまいます
![スクリーンショット 2020-02-13 1 28 51](https://user-images.githubusercontent.com/58411038/74355439-3b4ba080-4e00-11ea-9420-23d92017784b.png)

2020-02-13 12:11 UTC, Arisaarisa commented on index.php
> +  <?php foreach ($notyet_plans as $plan) : ?>
foreachの下に`<?php if (date('Y-m-d') >= $plan['due_date']) : ?>`から98行目のリストを持ってきてあげてください！
完了や編集よりも先に設定します！

2020-02-13 16:31 UTC, Yappiyapi commented
解決はできて追加や完了などはうまくいくんですが、こういったエラー表記が編集のときにでてしまいます。(編集自体はできているがindex.phpに戻れない)
if(count)の部分でなにか起きているということなのでしょうか？
![スクリーンショット 2020-02-14 1 02 28](https://user-images.githubusercontent.com/58411038/74455985-8382c580-4ec9-11ea-86dd-44f18bc4f129.png)
![スクリーンショット 2020-02-14 1 25 10](https://user-images.githubusercontent.com/58411038/74456149-b7f68180-4ec9-11ea-806e-b60505a62697.png)
![スクリーンショット 2020-02-14 1 25 00](https://user-images.githubusercontent.com/58411038/74456167-bd53cc00-4ec9-11ea-8fba-cc4a072e91bb.png)

2020-02-14 00:57 UTC, kazu-taka commented
@Yappiyapi 
現状、インデントがバラバラなので、コードをチェックする前にインデントの修正をお願いします:bow:
PHPのコードは不用な空白が入っていると警告がでる場合はあります。
修正して欲しい部分の一部を記載します！
<img width="583" alt="space" src="https://user-images.githubusercontent.com/5278718/74491853-383fd580-4f10-11ea-8624-f7fcdf8577c6.png">

また、formの中にulタグが入っていますが、pタグの外に出すようにして下さい！
```php
  <p>
    <form action="" method="post">
      <label for="title">学習内容:
        <input type="text" name="title">
      </label>
      <label for="due_date">期限日:
        <input type="date" name="due_date" id="">
        <input type="submit" value="編集">
      </label>
    </form>
  </p>
  <?php if (count($errors) > 0) : ?>
    <ul style="color:red;">
      <?php foreach ($errors as $key => $value) : ?>
        <li><?php echo h($value); ?></li>
      <?php endforeach; ?>
    </ul>
  <?php endif; ?>
```

コードの修正が終わったら、エラーのチェックします✨

2020-02-14 15:51 UTC, Yappiyapi commented
スペースとpタグ、formタグ修正しましたがまだどちらもwarningがでます。
![スクリーンショット 2020-02-15 0 51 30](https://user-images.githubusercontent.com/58411038/74546077-57307d00-4f8d-11ea-9e0b-2a54406f6189.png)
![スクリーンショット 2020-02-15 0 51 22](https://user-images.githubusercontent.com/58411038/74546081-5992d700-4f8d-11ea-8423-d46a7bb1dfc1.png)
![スクリーンショット 2020-02-15 0 51 10](https://user-images.githubusercontent.com/58411038/74546090-5d265e00-4f8d-11ea-87ed-acc69644d6ca.png)

2020-02-14 16:30 UTC, kazu-taka requested changes
@Yappiyapi 
コメントしたので修正お願いします✨

2020-02-14 16:30 UTC, kazu-taka commented on edit.php
> +  $errors['title'] = '学習内容を入力してください';
@Yappiyapi 
このへんのインデントもすべて修正お願いします:bow:
```php
  if ($title == '') {
    $errors['title'] = '学習内容を入力してください';
```

2020-02-14 16:30 UTC, kazu-taka commented on edit.php
> +      <title>編集画面</title>
@Yappiyapi 
インデントはすべて半角2文字でお願いします！

2020-02-14 16:30 UTC, kazu-taka commented on edit.php
> +    <?php if (count($errors) > 0) : ?>
@Yappiyapi 
$errorsは`if ($_SERVER['REQUEST_METHOD'] === 'POST') {`の中で初期化されているため、最初に表示される時に$errorsが初期化されていないため、存在しない変数へcountメソッドを使用しているため、警告が表示されています。
講義で説明した方法を使用してください✨
https://23seiki.gitbook.io/php/php/16#ermessjino

2020-02-15 16:35 UTC, Yappiyapi commented
確認お願いしますm(_ _)m

2020-02-16 04:21 UTC, kazu-taka requested changes
@Yappiyapi 
続きは後ほど確認します！

2020-02-16 04:21 UTC, kazu-taka commented on edit.php
> +        <input type="submit" value="編集">
@Yappiyapi 
編集ボタンはラベルの期限日には紐付かないので、labelの外に出しちゃってください！

2020-02-16 06:57 UTC, kazu-taka requested changes
@Yappiyapi 
コメントしたので修正お願いします！

2020-02-16 06:57 UTC, kazu-taka commented on index.php
> +  exit;
@Yappiyapi 
ifの中のインデントの修正をお願いします！

2020-02-16 06:57 UTC, kazu-taka commented on index.php
> +        <input type="submit" value="追加">
@Yappiyapi 
追加ボタンもラベルの外に出しちゃって下さい！

2020-02-16 13:14 UTC, Yappiyapi commented
修正完了しました！

2020-02-16 14:06 UTC, Arisaarisa commented on edit.php
> +  $sql = "update plans set (title, due_date, created_at, updated_at)
この下の内容がif文の中に含まれるように
インデントを修正してください！

2020-02-16 14:06 UTC, Arisaarisa commented on index.php
> +  <h2>達成済み</h2<ul>
</h2<ul>
になっているのでうまく認識されずすべてh2表示の大きさになっているので
>の追加と
インデントを直してください！

2020-02-16 15:26 UTC, Yappiyapi commented
再修正完了しました！

2020-02-17 02:34 UTC, Arisaarisa commented on index.php
>    <?php foreach ($done_plans as $plan) : ?>
ここはulタグの中に入るので恐らくざっとこのあたり一帯のインデントが正しい確認お願いします！

2020-02-17 03:25 UTC, Yappiyapi commented
インデント再修正完了しました！

2020-02-18 13:45 UTC, Arisaarisa commented
![LGTM](https://lgtmoon.herokuapp.com/images/75191)

2020-03-01 16:19 UTC, merged